#!/bin/sh
#
# xineshot
#
# A script to non interactively create whole window screenshots.
#
# Created for use with the Xine Multimedia Player.
#
# NB Xine must be in X Shared Memory mode for the xwd utility to
#    be able to capture the video output. In other modes the video
#    is drawn direct to hardware and is therefore unavailable
#    via the X server. There is a performance penulty for using XShm.
#
#    ie   xine -V XShm
#
# This script requires:
#   xwd      from the XFree86 package
#   xwdtopnm from the netpbm-progs package
#   pnmtopng from the netpbm-progs package
#   date     from the sh-utils package
#
# This script and the associated Xine patches are dedicated to
# Vicki Gynn <vicki@anvil.org> for whom it was created.
#
# Copyright 2001 (c) by Andrew Meredith <andrew@anvil.org>
#
# Creation Date: Tue Sep 25 2001
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

XWD=`which xwd`
XWDTOPNM=`which xwdtopnm`
PNMTOPNG=`which pnmtopng`
DT=`which date`

[ ! -x "${XWD}" ]      && echo "Cannot find the xwd program" && exit 1
[ ! -x "${XWDTOPNM}" ] && echo "Cannot find the xwdtopng program" && exit 1
[ ! -x "${PNMTOPNG}" ] && echo "Cannot find the pnmtopng program" && exit 1
[ ! -x "${DT}" ]       && echo "Cannot find the date program" && exit 1

OPFILE="${HOME}/xine-`${DT} '+%Y-%m-%d-%H%M%S'`.png"

EPRG="${XWD} -root | ${XWDTOPNM} | ${PNMTOPNG} > ${OPFILE}"

echo "${EPRG}"

eval ${EPRG}
