// xine interface definition

interface Xine
{
	// Open media and play it
	void play(in string MRL, in unsigned short position);

	// Toggle pause mode
	void pause();

	// Stop playing
	void stop();

	// Eject media
	long eject(in string MRL);

	// Current position in stream
	readonly attribute unsigned short position;

	// Player status
	enum PlayerStatus {
		statusStop,
		statusFillbuf,
		statusPlay,
		statusPause,
		statusQuit
	};
	readonly attribute PlayerStatus status;

	// Audio channel
	attribute unsigned short audioChannel;

	// SPU (subtitle) channel
	attribute unsigned short spuChannel;
};
