LIBCOMMON = $(top_builddir)/src/common/libcommon.a
LIBCOMMONX = $(top_builddir)/src/common/libcommonx.a

$(LIBCOMMON):
	$(MAKE) -C $(top_builddir)/src/common libcommon.a

$(LIBCOMMONX):
	$(MAKE) -C $(top_builddir)/src/common libcommonx.a

